FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

#SHELL ["sh", "-lc"]

RUN apt update
RUN apt install -y git python3 python3-pip

RUN python3 -m pip install --no-cache-dir --upgrade pip

ARG REF=main

WORKDIR /shared/workspace

RUN python3 -m pip install --no-cache-dir git+https://github.com/m-bain/whisperx.git

RUN apt install -y ffmpeg tmux

RUN python3 -m pip install --no-cache-dir pydub yt-dlp gdown